"""Generate source-derived capability coverage documents."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .capabilities import get_capabilities


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
FEATURE_MATRIX_PATH = DOCS_DIR / "FEATURE_MATRIX.yaml"
COVERAGE_REPORT_PATH = DOCS_DIR / "CAPABILITY_COVERAGE_REPORT.md"
GENERATOR_COMMAND = "python3 scripts/generate_capability_docs.py"
GENERATED_NOTICE = f"<!-- Generated by `{GENERATOR_COMMAND}`. Do not edit by hand. -->"
SUMMARY_STATUSES = ("supported", "partial", "unsupported")


def build_feature_matrix_manifest() -> dict[str, Any]:
    """Return a normalized docs manifest derived from the capability registry."""
    capabilities = get_capabilities()
    feature_graph = capabilities.get("feature_graph", {})
    entries = [
        {
            "id": feature_id,
            "status": str(metadata["status"]),
            "engine": str(metadata["engine"]),
            "test_ref": "tests/",
        }
        for feature_id, metadata in sorted(feature_graph.items())
    ]

    summary = {status: sum(1 for entry in entries if entry["status"] == status) for status in SUMMARY_STATUSES}
    summary["total_features"] = len(entries)

    return {
        "schema_version": str(capabilities["capabilities_schema_version"]),
        "summary": summary,
        "entries": entries,
    }


def render_feature_matrix_yaml(manifest: dict[str, Any] | None = None) -> str:
    """Render docs/FEATURE_MATRIX.yaml from the capability registry."""
    doc = manifest or build_feature_matrix_manifest()
    summary = doc["summary"]
    lines = [
        f'schema_version: "{doc["schema_version"]}"',
        "summary:",
        f'  total_features: {summary["total_features"]}',
        f'  supported: {summary["supported"]}',
        f'  partial: {summary["partial"]}',
        f'  unsupported: {summary["unsupported"]}',
        "entries:",
    ]
    for entry in doc["entries"]:
        lines.extend(
            [
                f'  - id: {entry["id"]}',
                f'    status: {entry["status"]}',
                f'    engine: {entry["engine"]}',
                f'    test_ref: {entry["test_ref"]}',
            ]
        )
    return "\n".join(lines) + "\n"


def render_capability_coverage_report(manifest: dict[str, Any] | None = None) -> str:
    """Render docs/CAPABILITY_COVERAGE_REPORT.md from the capability registry."""
    doc = manifest or build_feature_matrix_manifest()
    summary = doc["summary"]
    lines = [
        "# Capability Coverage Report",
        "",
        GENERATED_NOTICE,
        "",
        "## Snapshot",
        "- Source of truth: `cutagent_cli.capabilities.get_capabilities()`",
        "- Generated artifacts: `docs/FEATURE_MATRIX.yaml`, `docs/CAPABILITY_COVERAGE_REPORT.md`",
        f'- Schema version: `{doc["schema_version"]}`',
        f'- Total features: `{summary["total_features"]}`',
        f'- Supported: `{summary["supported"]}`',
        f'- Partial: `{summary["partial"]}`',
        f'- Unsupported: `{summary["unsupported"]}`',
        "",
        "## Release Gate",
        f'- Regenerate capability docs with `{GENERATOR_COMMAND}`.',
        "- CI runs `python3 scripts/feature_matrix_gate.py`.",
        "- Gate fails when schema version, summary totals, or any feature status/engine in `FEATURE_MATRIX.yaml` drifts from the capability registry.",
        "- Hosted CI runs lint + unit/contract + feature matrix gate only (`.github/workflows/ci.yml`).",
        "- Runtime DaVinci Resolve integration coverage is available as manual `workflow_dispatch` self-hosted job (`.github/workflows/runtime-integration.yml`).",
        "",
        "## Known Limits",
        "1. DaVinci Resolve API and DB-backed routes still do not expose every DaVinci Resolve workflow.",
        "2. Unsupported capabilities remain unsupported; discovery should not advertise GUI fallback routes.",
        "3. Runtime verification for partial/workaround features still depends on manual or live DaVinci Resolve coverage outside hosted CI.",
        "",
    ]
    return "\n".join(lines)


def write_generated_capability_docs(root: Path | None = None) -> dict[str, Path]:
    """Write the generated capability docs and return their paths."""
    base_dir = root or ROOT
    docs_dir = base_dir / "docs"
    manifest = build_feature_matrix_manifest()
    feature_matrix_path = docs_dir / FEATURE_MATRIX_PATH.name
    coverage_report_path = docs_dir / COVERAGE_REPORT_PATH.name
    feature_matrix_path.write_text(render_feature_matrix_yaml(manifest), encoding="utf-8")
    coverage_report_path.write_text(render_capability_coverage_report(manifest), encoding="utf-8")
    return {
        "feature_matrix": feature_matrix_path,
        "coverage_report": coverage_report_path,
    }
