/**
 * Agent-first authoring surface for the CutAgent SDK preview.
 *
 * Runtime validators and wire protocol machinery live at the explicit
 * `cutagent/schemas` and `cutagent/protocol` entry points.
 *
 * @packageDocumentation
 */

export { FUSION_REGISTRY } from "./fusion/generated/public-registry.js";
export type { GeneratedFusionNodeType, GeneratedFusionRegistry } from "./fusion/generated/public-registry.js";
export { advancedFusionRaw, validateAdvancedFusionRawRequest } from "./fusion/raw.js";
export type { AdvancedFusionRawRequest } from "./fusion/raw.js";
export {
  FusionGraphBuilder,
  FusionGraphValidationError,
  diagnoseFusionConnection,
  fusionFrame,
  fusionGraph,
  lowerFusionGraph,
  serializeFusionGraphRequest,
} from "./fusion/graph.js";
export type {
  Artifacts,
  ManagedArtifact,
  ManagedArtifactReceipt,
} from "./domain/artifacts.js";
export type {
  FusionAnimation,
  FusionAnimationFor,
  FusionAnimatableInputId,
  FusionCompatibleTargetPort,
  FusionConnectionDiagnostic,
  FusionConnectionEndpointDiagnostic,
  FusionConnectionTypeLabelRelation,
  FusionFrame,
  FusionGraphLoweringTarget,
  FusionGraphNodeMap,
  FusionGraphRequest,
  FusionInitialInputs,
  FusionInputId,
  FusionInputPort,
  FusionInputValue,
  FusionInputValueFor,
  FusionNodeByType,
  FusionNodeType,
  FusionOutputId,
  FusionOutputPort,
  FusionPortById,
  FusionRegistryGateOptions,
  FusionSettableInputId,
  FusionValueForDataType,
} from "./fusion/graph.js";
export {
  FUSION_GRAPH_APPLY_ACTION_ID,
  FUSION_IMAGE_REPLACE_ACTION_ID,
  FUSION_SETTINGS_INSERT_ACTION_ID,
  FUSION_TEXT_ACTION_ID,
  FUSION_NESTED_TEXT_ACTION_ID,
} from "./fusion/runtime.js";
export type {
  FusionComposition,
  FusionCompositionReference,
  FusionCompositions,
  FusionGraphApplyOptions,
  FusionGraphApplyResult,
  FusionGraphImpactPreview,
  FusionImageReplacement,
  FusionImageReplaceOptions,
  FusionImageReplaceResult,
  FusionSettingInsertion,
  FusionSettingsInsertOptions,
  FusionSettingsInsertResult,
  FusionTextOptions,
  FusionTextResult,
  FusionTextUpdate,
  FusionNestedTextItemResult,
  FusionNestedTextMutationOptions,
  FusionNestedTextMutationResult,
  FusionNestedTextUpdate,
} from "./fusion/runtime.js";
export type {
  FusionConnectionDefinition,
  FusionNodeDefinition,
  FusionPortDefinition,
  FusionRegistry,
  FusionRegistryDefinition,
} from "./fusion/registry.js";
export { CutAgent } from "./client.js";
export { LOW_LEVEL_READ_ACTION_IDS } from "./actions.js";
export type { TimelineFrameExportInput, TimelineFrameExportResult } from "./actions.js";
export type {
  ConnectionControlOptions,
  ConnectionSnapshot,
  CutAgentClient,
  CutAgentConnectOptions,
  RuntimeSelection,
} from "./client.js";
export type {
  ActionControlOptions,
  ActionPositiveInteger,
  ActionId,
  ActionInput,
  ActionInputMap,
  ActionResult,
  ActionResultMap,
  Actions,
  LowLevelActions,
  LowLevelReadActionId,
  LowLevelReadResult,
  OptionalIdempotencyActionId,
  OperationActionId,
  ReadActionId,
  SemanticReadActionId,
  RequiredActionControlOptions,
  RequiredIdempotencyActionId,
} from "./actions.js";
export type {
  ClipSnapshot,
  ColorInspector,
  ColorMutationCapability,
  ColorNodeSnapshot,
  ColorReadCapability,
  ColorTargetClipSnapshot,
  ColorTargetSnapshot,
  ColorTargetTrackSnapshot,
  Project,
  Projects,
  ReadControlOptions,
  Timeline,
  Timelines,
  TimelineSnapshot,
  TimelineTrackType,
  TrackSnapshot,
} from "./domain/object-model.js";
export { timelineActionContext, timelineRecordOffset } from "./domain/timeline-action-authoring.js";
export type {
  TimelineActionBinding,
  TimelineActionContext,
  TimelineBladeActionTarget,
  TimelineVideoActionTarget,
  TimelineVideoRetimeTarget,
} from "./domain/timeline-action-authoring.js";
export type {
  MediaPoolAsset,
  MediaPool,
  MediaPoolAssetKind,
  MediaPoolAssetSnapshot,
  MediaPoolFolderSnapshot,
  MediaPoolMetadataEntry,
  MediaPoolMetadataKey,
  MediaPoolTranscription,
  MediaPoolTranscriptionOptions,
  MediaPoolTranscriptionSegment,
  MediaPoolTranscriptionWord,
  MediaPoolMutationOptions,
  MediaPoolBin,
  MediaPoolCreateBinResult,
  MediaPoolDeleteItemResult,
  MediaPoolDeleteResult,
  MediaPoolImportResult,
  MediaPoolRelinkResult,
  MediaPoolSetMetadataResult,
  MediaPoolSyncAudioResult,
  MediaPoolPageOptions,
  MediaPoolSearchInput,
  MediaPoolSnapshotPage,
} from "./domain/media-pool.js";
export type {
  ProjectBackupResult,
  ProjectBoundMutations,
  ProjectRenameResult,
  ProjectSettingMutationResult,
  ProjectCollectionMutations,
  ProjectContextMutationResult,
  ProjectRestoreResult,
  ProjectContextObservation,
  ProjectLibraries,
  ProjectLibraryBackupResult,
  ProjectLibraryMutationResult,
  ProjectLibraryReference,
  ProjectMutationOptions,
  ProjectObservation,
  ProjectReference,
  ProjectRevisionObservation,
  TimelineObservation,
} from "./domain/project-management.js";
export type {
  MarkerActionId,
  MarkerImpactPreview,
  MarkerMutationBatchResult,
  MarkerMutationOptions,
  MarkerMutationResult,
  MarkerPreviewValues,
  Markers,
  MarkerSnapshot,
  MarkerUpdate,
  MarkerValues,
} from "./domain/markers.js";
export type {
  GeneratedVoiceAsset,
  Voice,
  VoiceCatalogEntry,
  VoiceCatalogPage,
  VoiceGenerationRequest,
  VoiceGenerationResult,
  VoiceOperationOptions,
  Voiceovers,
  VoicePlacementPreview,
  VoicePlacementResult,
} from "./domain/voice.js";
export type {
  LinkedAudioMovePolicy,
  TimelineItemMoveBatchResult,
  TimelineItemDurationChange,
  TimelineItemDurationObservation,
  TimelineItemDurationOptions,
  TimelineItemDurationResult,
  TimelineItemMoveBlocker,
  TimelineItemMoveDestination,
  TimelineItemMoveImpactPreview,
  TimelineItemMoveObservation,
  TimelineItemMoveOptions,
  TimelineItemMoveResult,
  TimelineItemMoveRequest,
  TimelineItemStateChangeInput,
  TimelineItemStateChangeObservation,
  TimelineItemStateChangeOptions,
  TimelineItemStateChangeResult,
  TimelineClipColorChange,
  TimelineClipColorObservation,
  TimelineClipColorResult,
  TimelineClipProperties,
  TimelineClipPropertyChange,
  TimelineClipPropertyObservation,
  TimelineClipPropertyOptions,
  TimelineClipPropertyResult,
  TimelineItems,
} from "./domain/timeline-items.js";
export type {
  AutoCaptionLanguage,
  AutoCaptionResult,
  CaptionControlOptions,
  CaptionSegmentation,
  CaptionTemplateSource,
  DesignedCaptionCue,
  DesignedCaptionResult,
  NativeSubtitleImportResult,
  SubtitleExportResult,
  SubtitleItemSnapshot,
  SubtitleSnapshot,
  TimelineCaptions,
  TimelineTranscript,
  TranscriptRelativeRange,
  TranscriptCreateOptions,
  TranscriptResult,
  TranscriptWord,
} from "./domain/captions.js";
export { transcriptRelativeRange } from "./domain/captions.js";
export type {
  Color,
  ColorActionId,
  ColorAssetReference,
  ColorEffect,
  ColorGradeAlignment,
  ColorImpactPreview,
  ColorMutation,
  ColorMutationOptions,
  ColorMutationResult,
  ColorNodeTopology,
  ColorPrimaryCorrection,
} from "./domain/color.js";
export {
  applyColorLut,
  applyColorStill,
  assignColorGroup,
  createColorRectangle,
  grabColorStill,
  matchColorShot,
  trackColorForward,
} from "./domain/color-workflows.js";
export type {
  ColorLutApplication,
  ColorLutOptions,
  ColorLutPluralRequest,
  ColorLutSingleRequest,
} from "./domain/color-workflows.js";
export type {
  ColorArtifactReference as ColorWorkflowArtifactReference,
  ColorGroupReference,
  ColorRectangleGeometry,
  ColorShotMatchOptions,
  ColorStillReference,
  ColorTrackerReference,
  ColorWorkflowActionId,
  ColorWorkflowRequest,
} from "./domain/color-workflows.js";
export type {
  Fairlight,
  FairlightActionId,
  FairlightBus,
  FairlightBusDirectory,
  FairlightChangeKind,
  FairlightClip,
  FairlightClipFadeBatchEntry,
  FairlightClipGainBatchEntry,
  FairlightClipPanBatchEntry,
  FairlightCrossfadeBatchEntry,
  FairlightClipState,
  FairlightDynamics,
  FairlightDynamicsProcessor,
  FairlightEqBand,
  FairlightImpactPreview,
  FairlightMutationOptions,
  FairlightMutationResult,
  FairlightObserved,
  FairlightPlan,
  FairlightRequestedChange,
  FairlightSemanticChange,
  FairlightSnapshot,
  FairlightTrack,
  FairlightTrackState,
} from "./domain/fairlight.js";
export {
  defineFairlightCrossfadeBatch,
  defineFairlightFadeInBatch,
  defineFairlightFadeOutBatch,
  defineFairlightGainBatch,
  defineFairlightPanBatch,
} from "./domain/fairlight.js";
export type {
  KnownRenderCodec,
  KnownRenderFormat,
  ProjectRender,
  RenderCodec,
  RenderCodecOption,
  RenderDiscovery,
  AudioRenderCodecOption,
  AudioRenderFormatOption,
  RenderFormat,
  RenderFormatOption,
  RenderJobSnapshot,
  RenderJobStatus,
  RenderMode,
  RenderRange,
  RenderArtifact,
  RenderArtifactMedia,
  RenderMutationCodec,
  RenderMutationFormat,
  RenderMutationOptions,
  RenderMutationRange,
  RenderMutationRequest,
  RenderMutationResult,
  RenderMutationSettings,
  RenderPreset,
  RenderPresetSnapshot,
  RenderQueue,
  RenderQueueListOptions,
  RenderQueuePage,
  RenderQueueStartOptions,
  RenderQueueStartResult,
  RenderResolution,
  RenderSettingsSnapshot,
  RenderSupport,
} from "./domain/render.js";
export type {
  TimelineEditAction,
  TimelineEditActionId,
  TimelineEditImpact,
  TimelineEditItemTarget,
  TimelineEditMutationOptions,
  TimelineEditMutationBatchResult,
  TimelineEditMutationResult,
  TimelineEditTrackTarget,
  TimelineEditor,
  TimelineAudioPlacementPreview,
  TimelineAudioPlacementPreviewOptions,
  TimelinePlacementPreview,
  TimelinePlacementPreviewOptions,
  TimelineRemovePreview,
  TimelineRemovePreviewOptions,
  TimelineTrimPreview,
  TimelineTrimEdgeDelta,
  TimelineTrimPreviewOptions,
} from "./domain/timeline-editing.js";
export {
  defineManagedTimeline,
  managedClip,
  managedOwnership,
  managedRegion,
  managedWholeTimeline,
  renderManagedTimelineDocument,
} from "./domain/managed-timeline.js";
export type {
  ManagedClip,
  ManagedOwnership,
  ManagedTimeline,
  ManagedTimelineApplication,
  ManagedTimelineApplyOptions,
  ManagedTimelineBinding,
  ManagedTimelineBlocker,
  ManagedTimelineDrift,
  ManagedTimelineDocument,
  ManagedTimelineDocumentV1,
  ManagedTimelineExportOptions,
  ManagedTimelineExportResult,
  ManagedTimelineExportSelection,
  ManagedTimelineCoverage,
  ManagedTimelinePreview,
  ManagedTimelineProgram,
  ManagedTimelineScope,
} from "./domain/managed-timeline.js";
export type {
  MulticamAngleSnapshot,
  MulticamCreateImpactPreview,
  MulticamCreateInput,
  MulticamCreateResult,
  MulticamFlattenImpactPreview,
  MulticamFlattenResult,
  MulticamMutationOptions,
  MulticamSnapshot,
  MulticamSourceInput,
  MulticamSourceSnapshot,
  MulticamSwitchImpactPreview,
  MulticamSwitchPoint,
  MulticamSwitchResult,
  MulticamTimelineResult,
  Multicams,
  TimelineMulticam,
} from "./domain/multicam.js";
export {
  CutAgentValueError,
  duration,
  frameRate,
  frames,
  framesToTimecode,
  seconds,
  sourcePosition,
  sourceRange,
  timecode,
  timecodeToFrames,
  timelineRecordPosition,
  timelineRecordRange,
} from "./value-types/time.js";
export type {
  BoundFrameDuration,
  BoundFrames,
  CutAgentValueErrorCode,
  Duration,
  FrameDuration,
  FrameRate,
  Frames,
  HydratedDuration,
  PositionValue,
  Seconds,
  SecondsDuration,
  SourcePosition,
  SourcePositionOf,
  SourceRange,
  SourceRangeOf,
  TimeRounding,
  Timecode,
  TimelineRecordPosition,
  TimelineRecordPositionOf,
  TimelineRecordRange,
  TimelineRecordRangeOf,
} from "./value-types/time.js";
export type {
  ArtifactId,
  ConnectionId,
  EvidenceId,
  ExecutionId,
  FusionCompositionId,
  IdempotencyKey,
  IncidentId,
  MediaPoolFolderId,
  MediaPoolItemId,
  MarkerId,
  MulticamAngleId,
  MulticamId,
  OperationId,
  OpaqueIdentity,
  ProjectId,
  RenderQueueCursor,
  RequestId,
  Revision,
  SdkSessionId,
  SnapshotTimelineItemId,
  SnapshotMediaPoolFolderId,
  SnapshotMediaPoolItemId,
  SnapshotRenderJobId,
  SnapshotTrackId,
  TimelineId,
  TimelineItemId,
  TrackIndex,
  WorkflowId,
} from "./value-types/identities.js";
export { artifactId, idempotencyKey, operationId, persistedIdempotencyKey, trackIndex } from "./value-types/identities.js";
export { CutAgentSdkError } from "./protocol/errors.js";
export type {
  FailureKind,
  PossibleMutationState,
  PublicErrorCause,
  PublicErrorCode,
  PublicFailure,
  Recovery,
  RecoveryOutcome,
  RetrySafetyProof,
  UsageState,
} from "./protocol/errors.js";
export type {
  AnyOperationHandle,
  MediaActionId,
  MediaActionResultValue,
  MediaExcludedActionId,
  MediaMutationResultData,
  MediaMutationResultDataByAction,
  MediaMutationActionId,
  MediaReadActionId,
  MediaReadResultData,
  MediaReadResultDataByAction,
  MediaResultApplicability,
  MediaResultEntity,
  MediaResultProperty,
  MediaResultVerification,
  MediaUnsupportedActionId,
  OperationCancellationRejected,
  OperationEvent,
  OperationHandle,
  OperationProgress,
  OperationRecovery,
  OperationRef,
  OperationResultCollectionReference,
  OperationResultPage,
  OperationResultPageOptions,
  Operations,
  OperationSnapshot,
  OperationSnapshotBase,
  OperationStatus,
  OperationSubscribeOptions,
  OperationWaitOptions,
  PublicActionContractVersion,
  PublicActionId,
  PublicActionResult,
  JsonValue,
  TerminalOperationFailure,
  TerminalOperationSnapshot,
  TerminalOperationSnapshotBase,
} from "./protocol/operations.js";
export { PUBLIC_ACTION_IDS } from "./protocol/operations.js";
export type {
  AuthoritativeWorkflowBinding,
  ManagedElementMapping,
  ManagedWorkflowState,
  ManagedWorkflowVerification,
  CheckpointWorkflowContext,
  CheckpointWorkflowOptions,
  WorkflowBinding,
  WorkflowJournal,
  WorkflowOperationHandle,
  WorkflowOutcome,
  WorkflowResult,
  WorkflowStepJournalEntry,
  WorkflowStepOutcome,
  WorkflowStepResult,
  Workflows,
} from "./core/workflows.js";
export {
  HIGH_LEVEL_WORKFLOW_EQUIVALENTS,
  defineOperationBatch,
  defineSelectedClipBatch,
  executeOperationBatch,
  planPodcastMulticamSwitches,
  planSilenceRetention,
  selectTimelineClips,
  validateOperationBatch,
} from "./domain/workflow-composition.js";
export type {
  HighLevelWorkflowEquivalent,
  HighLevelWorkflowEquivalentActionId,
  OperationBatch,
  OperationBatchResult,
  OperationBatchStep,
  OperationBatchValidation,
  PodcastMulticamPlan,
  PodcastSpeakerSegment,
  SelectedTimelineClip,
  SilenceRetentionPlan,
  TimelineClipPredicate,
  TimelineClipSelection,
} from "./domain/workflow-composition.js";
export type {
  EvidenceModality,
  VerificationEvidence,
  VerificationOutcome,
  VerificationReport,
} from "./protocol/verification.js";
export type {
  CapabilityAvailability,
  CapabilityEnvironment,
  CapabilityId,
  CapabilityReasonCode,
  DaVinciResolveEdition,
  Platform,
  PublicCapabilities,
  PublicCapability,
} from "./protocol/capabilities.js";
export type { CompatibilityDescriptor, RuntimeDistribution } from "./protocol/compatibility.js";
